apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/part-of: microservices-task
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
